### ISSUE TITLE
GLSL Shader Compilation issue with batch textures

### ISSUE THREAD

**Issue by athaun** [athaun/Gprocessing#1]
When running the program, shader compilation fails with this error.
```
[FATAL] Fragment shader compilation failed. Gprocessing.graphics.Window.initShaders()
	
0:16(27): error: sampler arrays indexed with non-constant expressions are forbidden in GLSL 1.30 and later
0:16(19): error: no matching function for call to `texture()'; candidates are:
0:16(19): error:    vec4 texture(sampler1D, float)
0:16(19): error:    ivec4 texture(isampler1D, float)
0:16(19): error:    uvec4 texture(usampler1D, float)
0:16(19): error:    vec4 texture(sampler2D, vec2)
0:16(19): error:    ivec4 texture(isampler2D, vec2)
0:16(19): error:    uvec4 texture(usampler2D, vec2)
0:16(19): error:    vec4 texture(sampler3D, vec3)
0:16(19): error:    ivec4 texture(isampler3D, vec3)
0:16(19): error:    uvec4 texture(usampler3D, vec3)
0:16(19): error:    vec4 texture(samplerCube, vec3)
0:16(19): error:    ivec4 texture(isamplerCube, vec3)
0:16(19): error:    uvec4 texture(usamplerCube, vec3)
0:16(19): error:    float texture(sampler1DShadow, vec3)
0:16(19): error:    float texture(sampler2DShadow, vec3)
0:16(19): error:    float texture(samplerCubeShadow, vec4)
0:16(19): error:    vec4 texture(sampler1DArray, vec2)
0:16(19): error:    ivec4 texture(isampler1DArray, vec2)
0:16(19): error:    uvec4 texture(usampler1DArray, vec2)
0:16(19): error:    vec4 texture(sampler2DArray, vec3)
0:16(19): error:    ivec4 texture(isampler2DArray, vec3)
0:16(19): error:    uvec4 texture(usampler2DArray, vec3)
0:16(19): error:    float texture(sampler1DArrayShadow, vec3)
0:16(19): error:    float texture(sampler2DArrayShadow, vec4)
0:16(19): error:    vec4 texture(sampler2DRect, vec2)
0:16(19): error:    ivec4 texture(isampler2DRect, vec2)
0:16(19): error:    uvec4 texture(usampler2DRect, vec2)
0:16(19): error:    float texture(sampler2DRectShadow, vec3)
0:16(19): error:    vec4 texture(sampler1D, float, float)
0:16(19): error:    ivec4 texture(isampler1D, float, float)
0:16(19): error:    uvec4 texture(usampler1D, float, float)
0:16(19): error:    vec4 texture(sampler2D, vec2, float)
0:16(19): error:    ivec4 texture(isampler2D, vec2, float)
0:16(19): error:    uvec4 texture(usampler2D, vec2, float)
0:16(19): error:    vec4 texture(sampler3D, vec3, float)
0:16(19): error:    ivec4 texture(isampler3D, vec3, float)
0:16(19): error:    uvec4 texture(usampler3D, vec3, float)
0:16(19): error:    vec4 texture(samplerCube, vec3, float)
0:16(19): error:    ivec4 texture(isamplerCube, vec3, float)
0:16(19): error:    uvec4 texture(usamplerCube, vec3, float)
0:16(19): error:    float texture(sampler1DShadow, vec3, float)
0:16(19): error:    float texture(sampler2DShadow, vec3, float)
0:16(19): error:    float texture(samplerCubeShadow, vec4, float)
0:16(19): error:    vec4 texture(sampler1DArray, vec2, float)
0:16(19): error:    ivec4 texture(isampler1DArray, vec2, float)
0:16(19): error:    uvec4 texture(usampler1DArray, vec2, float)
0:16(19): error:    vec4 texture(sampler2DArray, vec3, float)
0:16(19): error:    ivec4 texture(isampler2DArray, vec3, float)
0:16(19): error:    uvec4 texture(usampler2DArray, vec3, float)
0:16(19): error:    float texture(sampler1DArrayShadow, vec3, float)
0:16(10): error: operands to arithmetic operators must be numeric

[FATAL] Shader linking failed. Gprocessing.graphics.Window.initShaders()
	
error: linking with uncompiled/unspecialized shader
```

Offending file:
[default.glsl](https://github.com/athaun/Gprocessing/blob/master/src/assets/shaders/default.glsl)
[Window.java - compile() - line 136](https://github.com/athaun/Gprocessing/blob/master/src/Gprocessing/graphics/Shader.java)

**Comment by codingminecraft** [comment]
@GamesWithGabe here. There was an issue with your texture loading in render batch, but that's besides the point. I was able to run your project fine. Here's a screenshot: 

![tmp](https://user-images.githubusercontent.com/38877342/85629310-3e209280-b637-11ea-9545-79066da35601.png)

The one thing I did differently then you was I did not use the libraries you have included in your ```libs/``` directory. I'm guessing your version of GLFW is loading some older version of OpenGL. Inside your Engine.init function try:

``` 
System.out.println("Hello LWJGL " + Version.getVersion() + "!");
System.out.println(GLFW.glfwGetVersionString());
```

When I run that I get the output:

```
Hello LWJGL 3.2.3 build 13!
3.4.0 Win32 WGL EGL OSMesa VisualC DLL
```

I'm using Gradle to build all my files, which makes it easy to know exactly which versions of everything I'm getting. I'm guessing you're using an older version of the Win32 DLL. One other thing you need to change:

RenderBatch.java line 210
```
vertices[offset + 8] = textureID; // You had vertices[offset + 7] = textureID; 
```

That error threw me for a loop, if you don't have that index correct, you'll never end up loading any texture ID which means you won't end up seeing your texture even if the shader does compile. It also explains why when you tried to set the color to the tex coords it didn' do anything :)

**Comment by athaun** [comment]
Thanks for the fast response, this is what I get when running the getVersion methods:
```
Hello LWJGL 3.2.3 build 13!
3.4.0 X11 GLX EGL OSMesa clock_gettime evdev shared
```

> I'm guessing you're using an older version of the Win32 DLL.
My main development environment is actually linux, so I am not sure what the equivalent of the VisualC DLL is.
I will attempt to run this in windows, and see what happens

```
vertices[offset + 8] = textureID; // You had vertices[offset + 7] = textureID; 
```
Wow, thanks for catching that! that was very unintentional.

Also, in your video, you mentioned that openGL minimum specification requires atleast 16 texture slots, so even the lowest end GPU should have 16 slots right? If so, how come you suggested using 8?

And finally, I will try to get a different set of libraries and see if it will compile correctly.
Thanks!

**Comment by athaun** [comment]
Huh, very interesting, I set it up on windows, using the same libraries as on linux, and it works no problem.
![image](https://user-images.githubusercontent.com/32278830/85762584-ba16eb00-b6c8-11ea-9d60-85c913020097.png)

**Comment by codingminecraft** [comment]
Hey Asher, that was my other concern. The behavior of uploading the int array doesn't look like well-defined behavior by the OpenGL specifications. This goes into the reason that I used 8 texture slots, I originally only used 8 because I was hand writing something to emulate this, by basically having 8 unique uniforms that I upload too, then I would just choose the correct uniform. You can check it out at my old repo here: https://github.com/codingminecraft/Mario/blob/master/assets/shaders/default.glsl . The batched renderer should be mostly the same, except instead of uploading an int array, you upload a bunch of uniforms. You can check that out here: https://github.com/codingminecraft/Mario/blob/master/src/main/java/com/renderer/RenderBatch.java . Doing it this way is more cumbersome, but should result in well-defined behavior across platforms :)

**Comment by athaun** [comment]
I aksed for help on the Hopson community discord, and within a day, we got it all sorted out. Apparently, openGL minimum spec doesn't support dynamic indexing into a sampler2D array.
So, I replaced the main function with static indexing, and it works great.
```glsl
void main () {
    switch (int(fTexId)) {
        case 0:
            color = fColor;
            break;
        case 1:
            color = fColor * texture(uTextures[1], fTexCoords);
            break;
        case 2:
            color = fColor * texture(uTextures[2], fTexCoords);
            break;
        case 3:
            color = fColor * texture(uTextures[3], fTexCoords);
            break;
        case 4:
            color = fColor * texture(uTextures[4], fTexCoords);
            break;
        case 5:
            color = fColor * texture(uTextures[5], fTexCoords);
            break;
        case 6:
            color = fColor * texture(uTextures[6], fTexCoords);
            break;
        case 7:
            color = fColor * texture(uTextures[7], fTexCoords);
            break;
    }
}
```
@codingminecraft it might be a good idea for you to look into this, because your method worked fine on windows, but not on linux, and it might cause alot of issues later on for other linux users.

**Comment by codingminecraft** [comment]
@athaun I noticed your comment on the channel as well, thanks for posting that! And yea, I'm definitely going to release a video fixing this in the future, because I think I just ran into it on Windows :/ . I was trying it out on the channel because it seemed more elegant than the static indexing, but elegant isn't always correct, thanks for your help :)

**Comment by athaun** [comment]
No problem, glad I was able to help. :D
